export const BLOGS_PATH = 'data/blogs'
export const SERVICES_PATH = 'data/services'
export const EMPLOYEES_PATH = 'data/employees'
export const TESTIMONIALS_PATH = 'data/testimonials'
export const ABOUT_US_PATH = 'data/pages/about-us'
export const PRODUCT_PATH = 'data/product'
